### ISSUE TITLE
Not all Trello Labels Work

### ISSUE THREAD

**Issue by ober37** [MikoMagni/Alfrello#13]
Referencing the labels here:
http://help.trello.com/article/797-adding-labels-to-cards

I am able to create cards using the label color names in the link above for 1-6 (green - blue), however the remaining ones do not seem to work...

Any thoughts?

**Comment by anhtranghb** [comment]
same problems here, is this still active?

**Comment by MikoMagni** [comment]
Still here but with limited resources at the moment. Happy to merge if you find a solution.
