### ISSUE TITLE
Malformed input to a URL function

### ISSUE THREAD

**Issue by AuGaut** [MikoMagni/Alfrello#28]
Hy there
I keep getting logs of the following error:
[ 07:36:14] Curl error: URL rejected: Malformed input to a URL function
[ 07:44:13] Curl error: URL rejected: Malformed input to a URL function
[ 08:32:07] Curl error: URL rejected: Malformed input to a URL function
I followed the instructions when setting up the workflow. (Using Alfred 5.1.1 [2138])
Any way to help with this?
Much appreciated!

**Comment by AuGaut** [comment]
Hy @MikoMagni 

I installed PHP with the following command in the terminal: `/bin/bash -c "$(curl -fsSL https://github.com/alfredapp/dependency-scripts/raw/main/scripts/install-php.sh)"`

I have PHP 8.2.8 (cli) and the path is '/opt/homebrew/bin/php' from my home folder.

The logs list the errors shown in my initial comment.

Debugger looks as follows:
![image](https://github.com/MikoMagni/Alfrello/assets/139752337/e855d26f-e234-4070-9eb8-163730757463)

Thanks a lot for your help!

**Comment by AuGaut** [comment]
Update:

I think the problem was fixed when I deleted the workflow and reinstalled it. Maybe the dependency on php was not initialised properly. From my point of view I can close the issue.

**Comment by MikoMagni** [comment]
Excellent, I was just about to suggest a few more things. But I'm even happier that it is working 👍
