### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by ouvyt** [MikoMagni/Alfrello#6]
Hmm... I did the basic install:
1 - download the workflow
2 - got the token from trello
3 - added my board ID

But I am still getting the invalid argument error. I am not sure if I am missing something obvious. Any thoughts?

![screen shot 2014-11-14 at 9 24 02 am](https://cloud.githubusercontent.com/assets/9668092/5047111/02bb045c-6be0-11e4-95a6-8ab313f6eca5.png)

**Comment by petros** [comment]
Looks like I get the same error after following the instructions about the API token and Board ID. I am not sure what proxy you are referring to, and I can't find anything in Preferences other than:

<img width="490" alt="alfred_preferences" src="https://cloud.githubusercontent.com/assets/28818/9566491/45cdefca-4f10-11e5-8fee-577a38361134.png">

Which doesn't seem to make a difference.

Help? :smile:

**Comment by ouvyt** [comment]
Yup, that proxy setting made the difference :)

**Comment by petros** [comment]
Hmm, so in my case, I had to run the jello Alfred keyword to authorize it again, and use the new token. I created the first token manually first. Not sure if that was the problem though. Anyway, it works now.
